import {
	SiAngular,
	SiAnthropic,
	SiApacheavro,
	SiApachekafka,
	SiArchlinux,
	SiClaude,
	SiCss,
	SiCursor,
	SiDocker,
	SiDotnet,
	SiElasticsearch,
	SiExpress,
	SiFlask,
	SiGit,
	SiGithub,
	SiGo,
	SiGooglebigquery,
	SiGooglecloud,
	SiGrafana,
	SiGoogle,
	SiHtml5,
	SiJavascript,
	SiJenkins,
	SiKubernetes,
	SiLetsencrypt,
	SiModelcontextprotocol,
	SiMongodb,
	SiMysql,
	SiNeovim,
	SiNginx,
	SiNixos,
	SiOpenid,
	SiOpenapiinitiative,
	SiOpenjdk,
	SiOpensearch,
	SiPostgresql,
	SiPrometheus,
	SiPython,
	SiReact,
	SiReactivex,
	SiRedis,
	SiRust,
	SiSass,
	SiSvelte,
	SiTmux,
	SiTypescript,
} from '@icons-pack/svelte-simple-icons';
import { Cloud, DatabaseZap, Network } from 'lucide-svelte';
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const techIcons: Record<string, any> = {
	// Languages
	'Go':                    SiGo,
	'Python':                SiPython,
	'TypeScript':            SiTypescript,
	'JavaScript':            SiJavascript,
	'Java':                  SiOpenjdk,
	'HTML':                  SiHtml5,
	'CSS':                   SiCss,
	'SASS':                  SiSass,
	'C#':                    SiDotnet,

	// Backend
	'ASP.NET Core':          SiDotnet,
	'ExpressJs':             SiExpress,
	'Flask':                 SiFlask,
	'REST API':              SiOpenapiinitiative,
	'gRPC':                  SiGoogle,
	'BFF':                   Network,
	'OIDC':                  SiOpenid,
	'OAuth':                 SiOpenid,
	'IdentityServer':        SiOpenid,

	// Frontend
	'Svelte':                SiSvelte,
	'React':                 SiReact,
	'Angular':               SiAngular,
	'RxJS':                  SiReactivex,

	// Infrastructure
	'Kubernetes':            SiKubernetes,
	'Docker':                SiDocker,
	'Google Cloud':          SiGooglecloud,
	'Azure':                 Cloud,
	'Aiven':                 DatabaseZap,
	'Git':                   SiGit,
	'GitHub':                SiGithub,
	'Jenkins':               SiJenkins,

	// Messaging & Streaming
	'Kafka':                 SiApachekafka,
	'Avro':                  SiApacheavro,
	'Schema Registry':       SiApachekafka,

	// Observability
	'Grafana':               SiGrafana,
	'Prometheus':            SiPrometheus,

	// Data
	'PostgreSQL':            SiPostgresql,
	'MySQL':                 SiMysql,
	'MongoDB':               SiMongodb,
	'Redis':                 SiRedis,
	'BigQuery':              SiGooglebigquery,
	'Elasticsearch':         SiElasticsearch,
	'OpenSearch':            SiOpensearch,
	'Microsoft SQL':         SiDotnet,
	'EntityFramework Core':  SiDotnet,

	// Systems & OS
	'NixOS':                 SiNixos,
	'Nix':                   SiNixos,
	'Home Manager':          SiNixos,
	'Flakes':                SiNixos,
	'SOPS':                  SiLetsencrypt,
	'Arch Linux':            SiArchlinux,
	'Neovim':                SiNeovim,
	'Tmux':                  SiTmux,
	'Nginx':                 SiNginx,
	'Rust':                  SiRust,

	// AI & Tooling
	'Claude Code':           SiClaude,
	'OpenCode':              SiCursor,
	'MCP Servers':           SiModelcontextprotocol,
	'LLM Agents':            SiAnthropic,
};
